### ISSUE TITLE
Scrollbar missing on "Service-PopUp"

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1218]
Hey Sven,

I have installed the new Thruk release (3.00) on my test environment and it looks great!

I have found one thing, if I Click on the "Service Output" for a service that has "multiline" output and the output contains more lines than there are space on the screen, I do not get a scrollbar to scroll through the output (see screenshot).

![Screenshot_2022-11-18_15-04-00](https://user-images.githubusercontent.com/26163222/202724723-8ea9c465-2d32-42d5-8f92-2ae904645cee.png)

Is this a conscious GUI design or a bug?

Regards,
Dan

**Comment by sni** [comment]
i'd say this is a bug. It should be either visible or there should be a scrollbar. Just to understand you correctly, you'd expect a scrollbar in the popup, right?

**Comment by dan-m-joh** [comment]
Yes, in this case I am expecting a scrollbar (the output is >400 lines).

Dan

**Comment by sni** [comment]
fixed in 0c15a37429d9dbb706e3d16ff842d535c37c7694

**Comment by dan-m-joh** [comment]
Hello Sven,

I am sad to say that this problem still exists in 3.02.  (:-(

BUT, I have found out that is probably a Browser-issue.
Firefox - Linux - 102.6.0esr (64-bit) does not work.
Chromium - Linux - 108.0.5359.98 (64-bit) works.
Opera - Linux - 93.0.4585.64 works.
Firefox - Windows - 68.0.2 (64-bit) works.
Chrome - Windows - 108.0.5359.99 (Official Build) (64-bit) works.
PaleMoon - Windows - 31.4.1.1 (32 Bit) works.
Microsoft Edge - Windows - 108.0.1462.54 (Official build) (64-bit) works.

So it seems that it is probably only a problem with FF on Linux (which is my main Browser...).
