### ISSUE TITLE
Custom variables not searchable

### ISSUE THREAD

**Issue by sshmanko** [sni/Thruk#759]
Thruk: 2.16-2
LMD: 1.1.2
Nagios: 4.3.4
Livestatus: 1.2.8p25

1. If I understand correctly starting Thruk version 2.14-2 it should autocomplete custom variable values in search box, however after exposing them in config by adding: `show_custom_vars = *` nothing gets found (we use only host variables).

2. One suggestion on the same topic - custom variables on service pages should link to service details, not host details.
 Defined here:
https://github.com/sni/Thruk/blob/master/templates/extinfo_type_2.tt#L125
IMHO `[% IF cust.2 %]host[% END %]` should be removed

3. One more issue:
When showing all custom variables (*) they are missing from column configuration page.
https://www.thruk.org/documentation/dynamic-views.html#_adding-custom-variables
*[edit]* found a workaround: `show_custom_vars = *, VAR` - then VAR is added to custom column list

4. Another observation:
If you define `show_custom_vars = VAR` it is displayed on Host page only, Services under this host do not receive the custom variable (although they should inherit it). 
workaround: `show_custom_vars = VAR, HOSTVAR` 
Nagios prepends HOST to all host variables:
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/customobjectvars.html

**Comment by sni** [comment]
1. please try the nightly if possible, if i remember correctly, this should be fixed.
2. i agree, should be fixed in aecd7c3.
3. same as 1.
4. thats intentional to give you maximum options

**Comment by sshmanko** [comment]
thanks @sni, I did some testing today with 2.12 nightly build:
(with config option `show_custom_vars = *`)

1. Search in left sidebar still doesn't work with value from custom variable, however it works when clicked on variable name on the right side:

Search that doesn't work:
https://<ip>/thruk/#cgi-bin/status.cgi?s0_op=~&s0_type=search&add_default_service_filter=1&s0_value=ami-da1044cc

Filter that works:
https://<ip>/thruk/#cgi-bin/status.cgi?style=hostdetail&dfl_s0_type=custom+variable&dfl_s0_val_pre=AMI&dfl_s0_op=%3D&dfl_s0_value=ami-da1044cc&title=Host%20Status%20Details%20of%20AMI:%20ami-da1044cc

2. Is OK. Thanks!

3. Custom Vars did not appear in column configuration options - that is actually ok with us to define these vars explicitly, so it gives you choice which vars to display on page and which in column properties.

4. Fine with us.
